---
image: docker:///mischief/docker-golang

params:
  SEMVER_TESTING_ACCESS_KEY_ID:
  SEMVER_TESTING_SECRET_ACCESS_KEY:
  SEMVER_TESTING_BUCKET:
  SEMVER_TESTING_REGION:

paths:
  semver-resource: gopath/src/github.com/concourse/semver-resource

run:
  path: gopath/src/github.com/concourse/semver-resource/scripts/test
